### ISSUE TITLE
overlap_windows_sec overlap_sec argument

### ISSUE THREAD

**Issue by william-davies** [deepneuroscience/Rethinking-Eye-blink#2]
https://github.com/deepneuroscience/Rethinking-Eye-blink/blob/e4ad06008ac79735468ef7e2824cf906f4addcd7/rethinking_eyeblink/utils/slidingwin.py#L23-L36

I first thought the `overlap_sec` argument determined by how many seconds two adjacent windows overlapped. E.g. if `overlap_sec=3` and `window_size=30` then the first few windows would be:
* [0,30]
* [28,58]
* [56,86]
* [84,114]

Adjacent windows overlap by 3 seconds. E.g. 28s, 29s, 30s in the first two windows.

However, looking at the `overlap_windows_sec` implementation, `overlap` is added to `start` and `end` every iteration. Maybe I'm wrong, but would this not result in the following windows (same `overlap_sec` and `window_size` as previous example):
* [0,30]
* [3,33]
* [6,36]
* [9,39]

Here the windows overlap by 28 seconds, not 3 seconds. In which case `overlap_sec` is more like a `step_size` rather than an overlap? This seems to match page 6 of Cho 2021 too. Is this by design and I just misunderstood/misinterpreted the variable name?

Thank you and sorry if I'm just misunderstanding the code!

**Comment by deepneuroscience** [comment]
Yes you are right - the variable name is misleading, this has to be "step_size" or something
